### Get all songs
GET http://127.0.0.1:5000/api/songs/
Content-Type: application/json

###

### Add a new song
POST http://127.0.0.1:5000/api/songs/
Content-Type: application/json

{
    "title": "A new song",
    "artist": "A great artist"
}
